"""
plugins/pdf_export.py
PDF export — renders CompanySnapshot analysis to a branded PDF research report.

Primary API: PDFReportExporter
  .export_analysis(snapshot, ..., dest_dir=None) -> str (path)
  .export_peer_comparison(peer_result, ..., dest_dir=None) -> str (path)
  .export_scenario(scenario_result, ..., dest_dir=None) -> str (path)

Requires: fpdf2>=2.7.9 (pip install fpdf2)
"""

from __future__ import annotations

import logging
import os
from datetime import datetime
from typing import Optional

logger = logging.getLogger(__name__)

# ── fpdf2 availability guard ───────────────────────────────────────────────────
_FPDF_AVAILABLE = False
try:
    from fpdf import FPDF, XPos, YPos  # type: ignore
    _FPDF_AVAILABLE = True
except ImportError:
    FPDF = object  # type: ignore  # noqa: N818

# ── Brand colours (RGB) ───────────────────────────────────────────────────────
BRAND_COLOUR    = (30, 58, 138)    # Equilis navy
ACCENT_COLOUR   = (59, 130, 246)   # Equilis blue
RED_COLOUR      = (220, 38, 38)
AMBER_COLOUR    = (245, 158, 11)
GREEN_COLOUR    = (22, 163, 74)
GREY_TEXT       = (107, 114, 128)
BLACK           = (0, 0, 0)
WHITE           = (255, 255, 255)
LIGHT_GREY_BG   = (248, 250, 252)
TABLE_HEADER_BG = (30, 58, 138)

# ── Disclaimer text ───────────────────────────────────────────────────────────
DISCLAIMER_SHORT = (
    "Not investment advice. For research purposes only. "
    "Not SEBI-registered. Equilis India v1.0.0."
)

DISCLAIMER_FULL = (
    "This report has been generated by the Equilis India AI analysis system using "
    "publicly available data. It does not constitute investment advice, a solicitation, "
    "or a recommendation to buy, sell, or hold any security. All scenario outputs are "
    "mathematical computations of stated assumptions only - they are not price targets "
    "or earnings forecasts. Equilis India is not a SEBI-registered research analyst."
)

OUTPUT_DIR = os.path.expanduser("~/Downloads")


# ── EquilisPDF - branded FPDF2 subclass ───────────────────────────────────────

class EquilisPDF(FPDF):
    """
    Branded A4 PDF with auto header/footer.
    Every page carries company name + ticker (top-right) and disclaimer (bottom).
    """

    def __init__(self, company_name: str, ticker: str, report_date: str):
        if not _FPDF_AVAILABLE:
            raise ImportError("fpdf2 is required: pip install fpdf2>=2.7.9")
        super().__init__(orientation="P", unit="mm", format="A4")
        self.company_name = company_name
        self.ticker = ticker
        self.report_date = report_date
        self.set_auto_page_break(auto=True, margin=20)
        self.set_margins(15, 15, 15)

    # ------------------------------------------------------------------
    # Text sanitization -- built-in Helvetica/Courier fonts are latin-1
    # only. Replace common non-latin-1 characters with ASCII equivalents
    # so we never need a TTF font bundle.
    # ------------------------------------------------------------------
    _CHAR_MAP = str.maketrans({
        "\u2014": "-",    # em-dash
        "\u2013": "-",    # en-dash
        "\u2019": "'",    # right single quotation mark
        "\u2018": "'",    # left single quotation mark
        "\u201c": '"',    # left double quotation mark
        "\u201d": '"',    # right double quotation mark
        "\u20b9": "Rs.",  # Indian Rupee sign
        "\u2265": ">=",   # greater-than-or-equal
        "\u2264": "<=",   # less-than-or-equal
        "\u00d7": "x",    # multiplication sign
        "\u2026": "...",  # horizontal ellipsis
    })

    def normalize_text(self, text: str) -> str:  # type: ignore[override]
        """Sanitize to latin-1 before delegating to fpdf2's normalizer."""
        return super().normalize_text(text.translate(self._CHAR_MAP))

    def header(self):
        # Brand colour stripe
        self.set_fill_color(*BRAND_COLOUR)
        self.rect(0, 0, self.w, 12, "F")
        # Left: EQUILIS INDIA label
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(*WHITE)
        self.set_xy(15, 3)
        self.cell(80, 6, "EQUILIS INDIA - EQUITY RESEARCH")
        # Right: Company | Ticker | Date
        label = f"{self.company_name}  |  {self.ticker}  |  {self.report_date}"
        self.set_xy(self.w - 110, 3)
        self.cell(95, 6, label, align="R")
        self.set_text_color(*BLACK)
        self.ln(4)

    def footer(self):
        self.set_y(-14)
        self.set_draw_color(*BRAND_COLOUR)
        self.set_line_width(0.3)
        self.line(15, self.get_y(), self.w - 15, self.get_y())
        self.ln(1)
        self.set_font("Helvetica", "", 6)
        self.set_text_color(*GREY_TEXT)
        self.cell(150, 4, DISCLAIMER_SHORT)
        self.cell(0, 4, f"Page {self.page_no()}", align="R")
        self.set_text_color(*BLACK)


# ── PDFReportExporter - public API ─────────────────────────────────────────────

class PDFReportExporter:
    """
    Exports CompanySnapshot analysis to branded PDF reports.

    Usage:
        exporter = PDFReportExporter()
        path = exporter.export_analysis(snapshot, dest_dir="/tmp")
    """

    def __init__(self, dest_dir: Optional[str] = None):
        self._default_dest = dest_dir or OUTPUT_DIR

    # ── Public export methods ──────────────────────────────────────────────────

    def export_analysis(
        self,
        snapshot,
        dupont=None,
        cf_quality=None,
        red_flags=None,
        altman=None,
        validation_notes=None,
        dest_dir: Optional[str] = None,
    ) -> str:
        """
        Export a full equity analysis report to PDF.
        Returns the absolute path to the generated file.
        """
        company_name = getattr(snapshot, "company_name", "Unknown Company")
        ticker = getattr(snapshot, "ticker", "UNKNOWN").upper()
        date_str = datetime.now().strftime("%Y-%m-%d")

        pdf = EquilisPDF(company_name, ticker, date_str)
        pdf.add_page()

        self._section_cover(pdf, snapshot)
        self._section_overview(pdf, snapshot)
        self._section_income(pdf, snapshot)
        self._section_balance_sheet(pdf, snapshot)
        self._section_cash_flow(pdf, snapshot)
        self._section_shareholding(pdf, snapshot)
        if dupont:
            self._section_dupont(pdf, dupont)
        if cf_quality:
            self._section_cf_quality(pdf, cf_quality)
        if red_flags:
            self._section_red_flags(pdf, red_flags)
        if altman:
            self._section_altman(pdf, altman)
        self._section_disclaimer(pdf)

        return self._save(ticker, "ANALYSIS", pdf, dest_dir)

    def export_peer_comparison(self, peer_result, dest_dir: Optional[str] = None) -> str:
        """
        Export a peer comparison report to PDF.
        Returns the absolute path to the generated file.
        """
        ticker = getattr(peer_result, "ticker", "UNKNOWN").upper()
        company_name = getattr(peer_result, "company_name", ticker)
        date_str = datetime.now().strftime("%Y-%m-%d")

        pdf = EquilisPDF(company_name, ticker, date_str)
        pdf.add_page()

        self._section_peer_comparison(pdf, peer_result)
        self._section_disclaimer(pdf)

        return self._save(ticker, "PEER", pdf, dest_dir)

    def export_scenario(self, scenario_result, snapshot=None, dest_dir: Optional[str] = None) -> str:
        """
        Export a scenario analysis report to PDF.
        Returns the absolute path to the generated file.
        """
        ticker = getattr(scenario_result, "ticker", "UNKNOWN").upper()
        company_name = getattr(snapshot, "company_name", ticker) if snapshot else ticker
        date_str = datetime.now().strftime("%Y-%m-%d")

        pdf = EquilisPDF(company_name, ticker, date_str)
        pdf.add_page()

        self._section_scenario(pdf, scenario_result, snapshot)
        self._section_disclaimer(pdf)

        return self._save(ticker, "SCENARIO", pdf, dest_dir)

    # ── Section renderers ──────────────────────────────────────────────────────

    def _heading(self, pdf: "EquilisPDF", text: str, level: int = 1) -> None:
        if level == 1:
            pdf.set_fill_color(*ACCENT_COLOUR)
            pdf.set_text_color(*WHITE)
            pdf.set_font("Helvetica", "B", 11)
            pdf.cell(0, 8, f"  {text}", fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            pdf.set_text_color(*BLACK)
            pdf.ln(2)
        else:
            pdf.set_text_color(*BRAND_COLOUR)
            pdf.set_font("Helvetica", "B", 9)
            pdf.cell(0, 6, text, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            pdf.set_text_color(*BLACK)

    def _kv_grid(self, pdf: "EquilisPDF", items: list, cols: int = 2) -> None:
        """Render a key-value grid in `cols` columns."""
        col_width = (pdf.w - pdf.l_margin - pdf.r_margin) / cols
        for i, (label, value) in enumerate(items):
            if i % cols == 0 and i > 0:
                pdf.ln(0)
            x = pdf.l_margin + (i % cols) * col_width
            pdf.set_xy(x, pdf.get_y())
            pdf.set_font("Helvetica", "B", 8)
            pdf.cell(col_width * 0.4, 5, str(label) + ":", border=0)
            pdf.set_font("Helvetica", "", 8)
            pdf.cell(col_width * 0.6, 5, str(value), border=0,
                     new_x=XPos.RIGHT, new_y=YPos.NEXT if (i + 1) % cols == 0 else YPos.LAST)
        if len(items) % cols != 0:
            pdf.ln(5)
        pdf.ln(2)

    def _table(self, pdf: "EquilisPDF", headers: list, rows: list) -> None:
        """Render a simple table with column headers."""
        if not headers:
            return
        col_width = (pdf.w - pdf.l_margin - pdf.r_margin) / len(headers)
        # Header row
        pdf.set_fill_color(*TABLE_HEADER_BG)
        pdf.set_text_color(*WHITE)
        pdf.set_font("Helvetica", "B", 7)
        for h in headers:
            pdf.cell(col_width, 6, str(h), border=1, fill=True)
        pdf.ln()
        pdf.set_text_color(*BLACK)
        # Data rows
        pdf.set_font("Helvetica", "", 7)
        for i, row in enumerate(rows):
            if i % 2 == 0:
                pdf.set_fill_color(*LIGHT_GREY_BG)
            else:
                pdf.set_fill_color(*WHITE)
            for cell in row:
                pdf.cell(col_width, 5, str(cell), border=1, fill=True)
            pdf.ln()
        pdf.ln(2)

    def _source_note(self, pdf: "EquilisPDF", sources: list) -> None:
        """Render a small source attribution line."""
        if not sources:
            return
        pdf.set_font("Helvetica", "I", 6)
        pdf.set_text_color(*GREY_TEXT)
        note = "Sources: " + " | ".join(
            f"{s.source_name} ({s.fetched_at.strftime('%Y-%m-%d') if hasattr(s.fetched_at, 'strftime') else str(s.fetched_at)[:10]})"
            for s in sources[:3]
        )
        pdf.cell(0, 4, note, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_text_color(*BLACK)
        pdf.ln(1)

    def _section_cover(self, pdf: "EquilisPDF", snapshot) -> None:
        """Cover block with company name, ticker, CMP."""
        pdf.set_font("Helvetica", "B", 18)
        pdf.set_text_color(*BRAND_COLOUR)
        company_name = getattr(snapshot, "company_name", "") or ""
        pdf.cell(0, 12, company_name, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(*GREY_TEXT)
        ticker = getattr(snapshot, "ticker", "")
        exchange = getattr(snapshot, "exchange", "NSE")
        sector = getattr(snapshot, "sector", "")
        pdf.cell(0, 6, f"{ticker} | {exchange} | {sector}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_text_color(*BLACK)
        price = getattr(snapshot, "price", None)
        if price and getattr(price, "cmp", None):
            pdf.set_font("Helvetica", "B", 14)
            pdf.cell(0, 8, f"CMP: Rs.{price.cmp:,.2f}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.ln(4)

    def _section_overview(self, pdf: "EquilisPDF", snapshot) -> None:
        """Company overview key metrics grid."""
        self._heading(pdf, "Company Overview")
        mkt = getattr(snapshot, "market", None)
        price = getattr(snapshot, "price", None)
        inc = getattr(snapshot, "income", None)
        items = [
            ("Ticker",    getattr(snapshot, "ticker", "-")),
            ("Exchange",  getattr(snapshot, "exchange", "-")),
            ("Sector",    getattr(snapshot, "sector", "-")),
            ("Industry",  getattr(snapshot, "industry", "-")),
            ("Market Cap", f"Rs.{mkt.market_cap:,.0f} Cr" if mkt and mkt.market_cap else "-"),
            ("EV",        f"Rs.{mkt.enterprise_value:,.0f} Cr" if mkt and getattr(mkt, "enterprise_value", None) else "-"),
            ("52W High",  f"Rs.{price.week52_high:,.2f}" if price and price.week52_high else "-"),
            ("52W Low",   f"Rs.{price.week52_low:,.2f}" if price and price.week52_low else "-"),
            ("Revenue TTM", f"Rs.{inc.revenue_ttm:,.0f} Cr" if inc and inc.revenue_ttm else "-"),
            ("PAT TTM",   f"Rs.{inc.pat_ttm:,.0f} Cr" if inc and inc.pat_ttm else "-"),
        ]
        self._kv_grid(pdf, items, cols=2)
        if getattr(snapshot, "sources", None):
            self._source_note(pdf, snapshot.sources)

    def _section_income(self, pdf: "EquilisPDF", snapshot) -> None:
        """P&L section with TTM metrics and 5-year trend."""
        self._heading(pdf, "Profit & Loss")
        inc = getattr(snapshot, "income", None)
        if not inc:
            pdf.cell(0, 5, "Income data not available.", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            return
        items = [
            ("Revenue TTM",  f"Rs.{inc.revenue_ttm:,.0f} Cr" if inc.revenue_ttm else "-"),
            ("EBITDA TTM",   f"Rs.{inc.ebitda_ttm:,.0f} Cr" if inc.ebitda_ttm else "-"),
            ("PAT TTM",      f"Rs.{inc.pat_ttm:,.0f} Cr" if inc.pat_ttm else "-"),
            ("EPS TTM",      f"Rs.{inc.eps_ttm:,.2f}" if inc.eps_ttm else "-"),
            ("PAT Margin",   f"{inc.pat_ttm/inc.revenue_ttm*100:.1f}%" if (inc.pat_ttm and inc.revenue_ttm) else "-"),
            ("Gross Profit", f"Rs.{inc.gross_profit:,.0f} Cr" if getattr(inc, "gross_profit", None) else "-"),
        ]
        self._kv_grid(pdf, items, cols=2)

    def _section_balance_sheet(self, pdf: "EquilisPDF", snapshot) -> None:
        """Balance sheet summary."""
        self._heading(pdf, "Balance Sheet")
        bs = getattr(snapshot, "balance_sheet", None)
        if not bs:
            pdf.cell(0, 5, "Balance sheet data not available.", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            return
        items = [
            ("Total Assets",   f"Rs.{bs.total_assets:,.0f} Cr" if bs.total_assets else "-"),
            ("Total Debt",     f"Rs.{bs.total_debt:,.0f} Cr" if bs.total_debt else "-"),
            ("Equity",         f"Rs.{bs.equity:,.0f} Cr" if bs.equity else "-"),
            ("Cash",           f"Rs.{bs.cash:,.0f} Cr" if getattr(bs, "cash", None) else "-"),
            ("Current Assets", f"Rs.{bs.current_assets:,.0f} Cr" if bs.current_assets else "-"),
            ("Current Liab.",  f"Rs.{bs.current_liabilities:,.0f} Cr" if bs.current_liabilities else "-"),
        ]
        self._kv_grid(pdf, items, cols=2)

    def _section_cash_flow(self, pdf: "EquilisPDF", snapshot) -> None:
        """Cash flow section."""
        self._heading(pdf, "Cash Flow")
        cf = getattr(snapshot, "cash_flow", None)
        if not cf:
            pdf.cell(0, 5, "Cash flow data not available.", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            return
        items = [
            ("CFO TTM",   f"Rs.{cf.cfo_ttm:,.0f} Cr" if cf.cfo_ttm else "-"),
            ("CapEx TTM", f"Rs.{cf.capex_ttm:,.0f} Cr" if cf.capex_ttm else "-"),
            ("FCF TTM",   f"Rs.{cf.fcf_ttm:,.0f} Cr" if cf.fcf_ttm else "-"),
        ]
        self._kv_grid(pdf, items, cols=3)

    def _section_shareholding(self, pdf: "EquilisPDF", snapshot) -> None:
        """Shareholding pattern section."""
        self._heading(pdf, "Shareholding Pattern")
        sh = getattr(snapshot, "shareholding", None)
        if not sh:
            pdf.cell(0, 5, "Shareholding data not available.", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            return
        items = [
            ("Promoter",   f"{sh.promoter_holding:.1f}%" if sh.promoter_holding else "-"),
            ("FII",        f"{sh.fii_holding:.1f}%" if sh.fii_holding else "-"),
            ("DII",        f"{sh.dii_holding:.1f}%" if sh.dii_holding else "-"),
            ("Public",     f"{sh.public_holding:.1f}%" if sh.public_holding else "-"),
            ("Pledging",   f"{sh.promoter_pledging:.2f}%" if sh.promoter_pledging is not None else "-"),
        ]
        self._kv_grid(pdf, items, cols=3)

    def _section_dupont(self, pdf: "EquilisPDF", dupont) -> None:
        """DuPont ROE decomposition section."""
        self._heading(pdf, "DuPont ROE Decomposition")
        years = getattr(dupont, "years", [])
        roe   = getattr(dupont, "roe", [])
        npm   = getattr(dupont, "net_profit_margin", [])
        at    = getattr(dupont, "asset_turnover", [])
        lev   = getattr(dupont, "leverage", [])
        if years:
            rows = []
            for i, yr in enumerate(years):
                rows.append([
                    yr,
                    f"{roe[i]*100:.1f}%" if i < len(roe) and roe[i] is not None else "-",
                    f"{npm[i]*100:.1f}%" if i < len(npm) and npm[i] is not None else "-",
                    f"{at[i]:.2f}x" if i < len(at) and at[i] is not None else "-",
                    f"{lev[i]:.2f}x" if i < len(lev) and lev[i] is not None else "-",
                ])
            self._table(pdf, ["Year", "ROE", "NPM", "Asset TO", "Leverage"], rows)

    def _section_cf_quality(self, pdf: "EquilisPDF", cf_quality) -> None:
        """Cash flow quality section."""
        self._heading(pdf, "Cash Flow Quality")
        score = getattr(cf_quality, "score", None)
        grade = getattr(cf_quality, "grade", None)
        notes = getattr(cf_quality, "notes", [])
        if score is not None:
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(0, 6, f"Score: {score:.1f}/10  Grade: {grade or '-'}",
                     new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        for note in (notes or [])[:5]:
            pdf.set_font("Helvetica", "", 8)
            pdf.cell(0, 5, f"- {note}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.ln(2)

    def _section_red_flags(self, pdf: "EquilisPDF", red_flags) -> None:
        """Red flags forensic section."""
        self._heading(pdf, "Forensic Red Flags")
        flags = red_flags if isinstance(red_flags, list) else getattr(red_flags, "flags", [])
        if not flags:
            pdf.set_font("Helvetica", "", 8)
            pdf.cell(0, 5, "No significant red flags identified.", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            return
        for flag in flags[:10]:
            label = flag.get("flag", "") if isinstance(flag, dict) else str(flag)
            severity = flag.get("severity", "") if isinstance(flag, dict) else ""
            colour = RED_COLOUR if severity in ("HIGH", "CRITICAL") else AMBER_COLOUR
            pdf.set_fill_color(*colour)
            pdf.set_text_color(*WHITE)
            pdf.set_font("Helvetica", "B", 7)
            pdf.cell(18, 5, severity or "FLAG", fill=True)
            pdf.set_text_color(*BLACK)
            pdf.set_font("Helvetica", "", 8)
            pdf.cell(0, 5, f" {label}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.ln(2)

    def _section_altman(self, pdf: "EquilisPDF", altman: dict) -> None:
        """Altman Z-Score section."""
        self._heading(pdf, "Altman Z-Score (Academic Reference)")
        if altman.get("skipped"):
            pdf.set_font("Helvetica", "I", 8)
            pdf.cell(0, 5, f"Skipped: {altman.get('reason', '')}",
                     new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            return
        z    = altman.get("z_score")
        zone = altman.get("zone", "")
        colour = GREEN_COLOUR if zone == "SAFE" else (AMBER_COLOUR if zone == "GREY" else RED_COLOUR)
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(*colour)
        pdf.cell(0, 8, f"Z-Score: {z:.4f}  |  Zone: {zone}",
                 new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_text_color(*BLACK)
        pdf.cell(0, 5, altman.get("zone_description", ""), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        comps = altman.get("components", {})
        items = [(k, f"{v:.4f}") for k, v in comps.items()]
        self._kv_grid(pdf, items, cols=3)
        pdf.set_font("Helvetica", "I", 7)
        pdf.set_text_color(*GREY_TEXT)
        pdf.multi_cell(0, 4, altman.get("disclaimer", ""))
        pdf.set_text_color(*BLACK)
        pdf.ln(2)

    def _section_peer_comparison(self, pdf: "EquilisPDF", peer_result) -> None:
        """Peer comparison table section."""
        self._heading(pdf, "Peer Comparison")
        ticker = getattr(peer_result, "ticker", "-")
        sector = getattr(peer_result, "sector", "-")
        universe_size = getattr(peer_result, "universe_size", "-")
        items = [
            ("Ticker",    ticker),
            ("Sector",    sector),
            ("Universe",  str(universe_size)),
            ("Timestamp", datetime.now().strftime("%Y-%m-%d")),
        ]
        self._kv_grid(pdf, items, cols=2)
        peers = getattr(peer_result, "peers", [])
        if peers:
            rows = []
            for p in peers[:20]:
                rows.append([
                    getattr(p, "ticker", "-"),
                    f"{getattr(p, 'pe_ratio', None):.1f}" if getattr(p, 'pe_ratio', None) else "-",
                    f"{getattr(p, 'roe', None)*100:.1f}" if getattr(p, 'roe', None) else "-",
                    f"{getattr(p, 'pat_margin', None)*100:.1f}" if getattr(p, 'pat_margin', None) else "-",
                    f"{getattr(p, 'market_cap', None):,.0f}" if getattr(p, 'market_cap', None) else "-",
                ])
            self._table(pdf, ["Ticker", "PE", "ROE%", "PAT Margin%", "Mkt Cap Cr"], rows)
        else:
            pdf.set_font("Helvetica", "I", 8)
            pdf.cell(0, 5, "No peer data available.", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    def _section_scenario(self, pdf: "EquilisPDF", scenario_result, snapshot=None) -> None:
        """Scenario analysis section."""
        self._heading(pdf, "Scenario Analysis")
        base_iv = getattr(scenario_result, "base_iv", None)
        items = [
            ("Company",   getattr(snapshot, "company_name", "-") if snapshot else "-"),
            ("Ticker",    getattr(snapshot, "ticker", "-") if snapshot else "-"),
            ("Base IV",   f"Rs.{base_iv:,.2f}" if base_iv else "-"),
        ]
        self._kv_grid(pdf, items, cols=2)
        scenarios = getattr(scenario_result, "scenarios", [])
        if scenarios:
            rows = [[
                getattr(s, "label", "-"),
                f"{getattr(s, 'pat_growth_rate', 0)*100:.1f}%",
                f"Rs.{getattr(s, 'intrinsic_value', 0):,.2f}" if getattr(s, 'intrinsic_value', None) else "-",
            ] for s in scenarios]
            self._table(pdf, ["Scenario", "Growth Rate", "IV/Share"], rows)

    def _section_disclaimer(self, pdf: "EquilisPDF") -> None:
        """Full compliance disclaimer section."""
        self._heading(pdf, "Compliance Disclaimer")
        pdf.set_font("Helvetica", "", 7)
        pdf.set_text_color(*GREY_TEXT)
        pdf.multi_cell(0, 4, DISCLAIMER_FULL)
        pdf.set_text_color(*BLACK)
        pdf.ln(2)

    # ── File save helper ───────────────────────────────────────────────────────

    def _save(
        self,
        ticker: str,
        label: str,
        pdf: "EquilisPDF",
        dest_dir: Optional[str] = None,
    ) -> str:
        """Save the PDF and return the absolute file path."""
        directory = dest_dir or self._default_dest
        os.makedirs(directory, exist_ok=True)
        date_str = datetime.now().strftime("%Y%m%d")
        filename = f"{ticker.upper()}_equilis_{label.upper()}_{date_str}.pdf"
        filepath = os.path.join(directory, filename)
        pdf.output(filepath)
        logger.info(f"[pdf_export] Saved {label} report to {filepath}")
        return filepath


# ── Legacy shim for backwards compatibility ────────────────────────────────────

class PdfExportPlugin:
    """
    Legacy class — use PDFReportExporter for new code.
    Wraps PDFReportExporter for backward compatibility.
    """

    def __init__(self, output_dir: str = OUTPUT_DIR):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def render_markdown_to_pdf(self, markdown_text: str, ticker: str) -> str:
        """
        Convert a markdown string to a PDF file (legacy method).
        Returns absolute path to the generated file.
        """
        date_str = datetime.now().strftime("%Y%m%d")
        filename = f"{ticker.upper()}_{date_str}.pdf"
        out_path = os.path.join(self.output_dir, filename)
        self._render_fpdf(markdown_text, out_path)
        return out_path

    def _render_fpdf(self, markdown_text: str, out_path: str) -> None:
        """Minimal plain-text renderer using fpdf2."""
        if not _FPDF_AVAILABLE:
            raise ImportError("fpdf2 is required: pip install fpdf2>=2.7.9")
        pdf = FPDF()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.set_font("Helvetica", size=10)
        for line in markdown_text.split("\n"):
            clean = line.lstrip("#").strip()
            if line.startswith("# "):
                pdf.set_font("Helvetica", style="B", size=14)
                pdf.cell(0, 8, clean, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
                pdf.set_font("Helvetica", size=10)
            elif line.startswith("## "):
                pdf.set_font("Helvetica", style="B", size=12)
                pdf.cell(0, 7, clean, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
                pdf.set_font("Helvetica", size=10)
            else:
                pdf.multi_cell(0, 5, clean)
        pdf.output(out_path)

